all:
    children:

        vpn:
           children:
               c1:
                   hosts:
                       c1n1:
                           ansible_host: 178.62.59.224
                   vars:
                       cluster_vpn_settings_dir_source: files/staging/vpn/openvpn/c1
                       cluster_vpn_settings_dir_dest: "{{docker_persistent_dir}}/openvpn"
                       ufw_allow_port:
                        - 443
                        - 22

#               c2:
#                   hosts:
#                       c2n1:
#                           ansible_host: 46.101.24.75
#                       c2n2:
#                           ansible_host: 46.101.24.75
#                   vars:
#                      cluster_vpn_settings_dir_source: files/staging/vpn/openvpn/c2
#                      cluster_vpn_settings_dir_dest: "{{docker_persistent_dir}}/openvpn"
#                      ufw_allow_port:
#                        - 443
#                        - 22

    vars:
        ansible_port: 22
        ansible_user: deploy
        ansible_sudo_pass: aksdnv764VGGHS2636sFCrfcasasdfca
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
        ansible_python_interpreter: /usr/bin/python2.7
        ansible_ssh_private_key_file: files/staging/keys/id_rsa

        application_name: onetimevpn
        destination_project_dir: "/home/{{ansible_user}}/{{application_name}}"
        docker_persistent_dir: "/home/{{ansible_user}}/{{application_name}}/docker_persistent"
