# Tested at:
# Ubuntu 16.04
# Ubuntu 18.04

---
- name: Build image
  hosts: c1
  tasks:
    - name: Building image
      sudo: yes
      raw: "cd \"$(dirname \"{{ docker_compose_dest }}\")\" && docker-compose build --force-rm --no-cache"
